name: Build

on:
  push:
    branches: ["main", "developer"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v3

      - name: Version
        id: semantic
        uses: codfish/semantic-release-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Build
        run: make build APP=caos VERSION=${{ steps.semantic.outputs.version }}
