name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ 'macos-latest' || 'ubuntu-latest' || 'windows-latest' }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Versioned
        id: semantic
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Build
        run: make build APP=caos VERSION=${{steps.semantic.outputs.version}}
